name: Sync Open-WebUI

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Add Open-WebUI repository as remote
      run: |
        git remote add open-webui https://github.com/open-webui/open-webui.git
        git fetch open-webui

    - name: Merge changes from Open-WebUI
      run: |
        git checkout main
        git pull origin main
        git merge open-webui/main --strategy-option theirs

    - name: Push changes to your repository
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
